### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by cid2105** [welch/seasonal#2]
ubuntu@ip-172-31-0-9:~/Sites/dashboard/seasonal$ seasonal --plot data/misc/logAirPassengers.12.csv
period  %TEV    %EEV    N       cycles  file
Traceback (most recent call last):
  File "/usr/local/bin/seasonal", line 9, in <module>
    load_entry_point('seasonal', 'console_scripts', 'seasonal')()
  File "/home/ubuntu/Sites/dashboard/seasonal/seasonal/application.py", line 117, in seasonal_cmd
    csvpath, column=options.column, split=options.split)
  File "/home/ubuntu/Sites/dashboard/seasonal/seasonal/application.py", line 46, in read_csv
    data = pd.read_csv(path, index_col=0, parse_dates=0)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1202, in __init__
    ParserBase.**init**(self, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 893, in **init**
    kwds.pop('parse_dates', False))
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 873, in _validate_parse_dates_arg
    raise TypeError(msg)
TypeError: Only booleans, lists, and dictionaries are accepted for the 'parse_dates' parameter

**Comment by cid2105** [comment]
I am using pandas 0.18.1, numpy 1.11.0, scipy 0.17.1,

**Comment by welch** [comment]
Thanks for the heads-up. Looks like, in application.py, the parse_dates=0 should be parse_dates=False (I'm running pandas 0.18.0, a minor behind you, which accepts this).

It will be a few days before I can turn this around (interviews!), but if you wanted to bundle it into PR with a proper unit test I'll give it attention sooner.

**Comment by welch** [comment]
fixed in version 0.3.1

**Comment by cid2105** [comment]
thank you for fixing this. good luck on your interviews, Will!
